name: Build EXE
on:
  workflow_dispatch:
  push:
    branches:
      - "develop"    # 或者 "master"，根据你的默认分支名称修改
permissions:
  contents: write # 必须权限：允许修改 Release 和 Tag

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python (32-bit)
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          architecture: x86
      - name: Install poetry
        uses: abatilo/actions-poetry@v4
      - name: Register gbda_aut.dll
        run: |
          Copy-Item .\lib\gbda_aut.dll C:\Windows\System32\
          regsvr32 /s C:\Windows\System32\gbda_aut.dll
        shell: pwsh
      - name: Install dependencies
        run: poetry install
      - name: Build executables
        run: scripts/build_executables.ps1
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "latest-003"
          artifacts: |
            dist/OpenOpcCli.exe
            dist/OpenOpcServer.exe
            dist/OpenOpcService.exe
